noun = input("Gimme a noun. ")
adjective = input("How 'bout an adjective? ")
adverb = input("Can I get an adverb? ")
verb = input("and finally, how 'bout a verb? ")
print("On a tropical " + noun + "," + " Underneath a " + adjective + " lava moon. " + "Hangin' " + adverb + " with the hula dancers," + verb + " questions cause' they got all the answers.")